// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace @KafkaWorker.Sample
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class AvroOrderMessage : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""AvroOrderMessage"",""namespace"":""KafkaWorker.Sample"",""fields"":[{""name"":""OrderId"",""type"":""int""},{""name"":""SellerId"",""type"":[""string"",""null""]},{""name"":""OrderDate"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}},{""name"":""Total"",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":10,""scale"":2}}]}");
		private int _OrderId;
		private string _SellerId;
		private System.DateTime _OrderDate;
		private Avro.AvroDecimal _Total;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AvroOrderMessage._SCHEMA;
			}
		}
		public int OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		public string SellerId
		{
			get
			{
				return this._SellerId;
			}
			set
			{
				this._SellerId = value;
			}
		}
		public System.DateTime OrderDate
		{
			get
			{
				return this._OrderDate;
			}
			set
			{
				this._OrderDate = value;
			}
		}
		public Avro.AvroDecimal Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				this._Total = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.SellerId;
			case 2: return this.OrderDate;
			case 3: return this.Total;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Int32)fieldValue; break;
			case 1: this.SellerId = (System.String)fieldValue; break;
			case 2: this.OrderDate = (System.DateTime)fieldValue; break;
			case 3: this.Total = (Avro.AvroDecimal)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
